"""
Test strings and constants for Turkish text normalization.
"""

# Turkish alphabet and vowels
TURKISH_ALPHABET_SMALL = "abcçdefgğhıijklmnoöprsştuüvyz"
TURKISH_ALPHABET_CAPITAL = "ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ"
BACK_VOWELS = "aıouûâ"
FRONT_VOWELS = "eiöüîêô"
TURKISH_VOWELS = BACK_VOWELS + FRONT_VOWELS

sapka_test_sentences = {
    'Â: Türkçede kullanılır. Hafif uzun, ince bir "a" sesidir. Kural olarak bu inceliğin tam olarak sağlanabilmesi için biraz uzatılması gerekir. Örneğin kâr, hâlâ, Kâzım, Nâzım, âlem, kâğıt…': 'A: Türkçede kullanılır. Hafif uzun, ince bir "a" sesidir. Kural olarak bu inceliğin tam olarak sağlanabilmesi için biraz uzatılması gerekir. Örneğin kar, hala, Kazım, Nazım, alem, kağıt…',
    'Û: Türkçede kullanılır. Hafif uzatılarak okunan ince bir "u" sesidir. Doğru kullanım için kural olarak biraz uzatılması gerekir. Örneğin sükûnet, mûris, mûzip, sûni…': 'U: Türkçede kullanılır. Hafif uzatılarak okunan ince bir "u" sesidir. Doğru kullanım için kural olarak biraz uzatılması gerekir. Örneğin sükunet, muris, muzip, suni…',
    'Î: Türkçede kullanılır. Uzatılarak okunan ince bir "i" sesidir. Kullanımda harfindeki noktanın üzerine işaret koyulması, çift noktalama gerektirdiğinden yalnızca düzeltme imi kullanılır, nokta düşer. Örneğin millî, dinî, dîdem, îzan, mîde...': 'İ: Türkçede kullanılır. Uzatılarak okunan ince bir "i" sesidir. Kullanımda harfindeki noktanın üzerine işaret koyulması, çift noktalama gerektirdiğinden yalnızca düzeltme imi kullanılır, nokta düşer. Örneğin milli, dini, didem, izan, mide...',
}


ile_test_words = {
    "Toros": "Torosla",
    "Ankara": "Ankarayla",
    "Konya": "Konyayla",
    "İstanbul": "İstanbulla",
    "Çay": "Çayla",
    "Ali": "Aliyle",
    "Alp": "Alpla",
    "dükkân": "dükkânla",
    "Dy": "Dy ile",
    "S": "S ile",
    "x": "x ile",
    "AB": "AB ile",
}

ise_test_words = {
    "Toros": "Torossa",
    "Ankara": "Ankaraysa",
    "Konya": "Konyaysa",
    "İstanbul": "İstanbulsa",
    "Çay": "Çaysa",
    "Ali": "Aliyse",
    "Alp": "Alpsa",
    "dükkân": "dükkânsa",
    "Alkollü": "Alkollüyse",
    "Kontrol": "Kontrolse",
    "Z": "Z ise",
    "BB": "BB ise",
    "x": "x ise",
}

# Ek-fiilin zarf-fiil eki almış biçimi olan iken ayrı yazılabildiği gibi kelimelere eklenerek de yazılabilir.
# Eklenerek yazıldığında baştaki i düşer. Eklendiği kelimenin ünlüleri kalın olsa da -ken zarf-fiil ekinin ünlüsü ince kalır:
# başlayacak-ken (başlayacak iken), çalışıyor-ken (çalışıyor iken), durgun-ken (durgun iken), okur-ken (okur iken),
# olgun-ken (olgun iken), uyur-ken (uyur iken), yazar-ken (yazar iken); geliyor-ken (geliyor iken), gülmüş-ken (gülmüş iken),
# öğretmen-ken (öğretmen iken) vb.

# iken, ünlüyle biten kelimelere bitişik olarak yazıldığında araya y ünsüzü girer ve başındaki i ünlüsü düşer:
# evde-y-ken (evde iken), okulda-y-ken (okulda iken), okumakta-y-ken (okumakta iken), yolda-y-ken (yolda iken) vb.
iken_test_words = {
    "başlayacak": "başlayacakken",
    "çalışıyor": "çalışıyorken",
    "durgun": "durgunken",
    "okur": "okurken",
    "olgun": "olgunken",
    "uyur": "uyurken",
    "yazar": "yazarken",
    "geliyor": "geliyorken",
    "gülmüş": "gülmüşken",
    "öğretmen": "öğretmenken",
    "evde": "evdeyken",
    "okulda": "okuldayken",
    "okumakta": "okumaktayken",
    "yolda": "yoldayken",
    "Dy": "Dy iken",
    "S": "S iken",
    "x": "x iken",
    "AB": "AB iken",
}

istisnalar_test_words = {
    "akropol": ("akropolle", "akropolse"),
    "alkol": ("alkolle", "alkolse"),
    "alveol": ("alveolle", "alveolse"),
    "amiral": ("amiralle", "amiralse"),
    "anormal": ("anormalle", "anormalse"),
    "antimikrobiyal": ("antimikrobiyalle", "antimikrobiyalse"),
    "antiviral": ("antiviralle", "antiviralse"),
    "atol": ("atolle", "atolse"),
    "azol": ("azolle", "azolse"),
    "bandrol": ("bandrolle", "bandrolse"),
    "başrol": ("başrolle", "başrolse"),
    "bemol": ("bemolle", "bemolse"),
    "berkemal": ("berkemalle", "berkemalse"),
    "bienal": ("bienalle", "bienalse"),
    "biomedikal": ("biomedikalle", "biomedikalse"),
    "biyomedikal": ("biyomedikalle", "biyomedikalse"),
    "brakisefal": ("brakisefalle", "brakisefalse"),
    "celal": ("celalle", "celalse"),
    "cemal": ("cemalle", "cemalse"),
    "deccal": ("deccalle", "deccalse"),
    "desimal": ("desimalle", "desimalse"),
    "diagonal": ("diagonalle", "diagonalse"),
    "dijital": ("dijitalle", "dijitalse"),
    "diastol": ("diastolle", "diastolse"),
    "diyagonal": ("diyagonalle", "diyagonalse"),
    "diyastol": ("diyastolle", "diyastolse"),
    "dömifinal": ("dömifinalle", "dömifinalse"),
    "efdal": ("efdalle", "efdalse"),
    "ekol": ("ekolle", "ekolse"),
    "ekstrasistol": ("ekstrasistolle", "ekstrasistolse"),
    "emsal": ("emsalle", "emsalse"),
    "etanol": ("etanolle", "etanolse"),
    "etfal": ("etfalle", "etfalse"),
    "faul": ("faulle", "faulse"),
    "federal": ("federalle", "federalse"),
    "feldmareşal": ("feldmareşalle", "feldmareşalse"),
    "fenol": ("fenolle", "fenolse"),
    "feodal": ("feodalle", "feodalse"),
    "festival": ("festivalle", "festivalse"),
    "fetal": ("fetalle", "fetalse"),
    "final": ("finalle", "finalse"),
    "fleol": ("fleolle", "fleolse"),
    "fol": ("folle", "folse"),
    "fümerol": ("fümerolle", "fümerolse"),
    "general": ("generalle", "generalse"),
    "glikol": ("glikolle", "glikolse"),
    "global": ("globalle", "globalse"),
    "gol": ("golle", "golse"),
    "gribal": ("griballe", "gribalse"),
    "hakikat": ("hakikatle", "hakikatse"),
    "hayal": ("hayalle", "hayalse"),
    "helal": ("helalle", "helalse"),
    "hidrozol": ("hidrozolle", "hidrozolse"),
    "hidrotermal": ("hidrotermalle", "hidrotermalse"),
    "hilal": ("hilalle", "hilalse"),
    "hiperbol": ("hiperbolle", "hiperbolse"),
    "hol": ("holle", "holse"),
    "ideal": ("idealle", "idealse"),
    "idol": ("idolle", "idolse"),
    "iğfal": ("iğfalle", "iğfalse"),
    "ihlal": ("ihlalle", "ihlalse"),
    "ihmal": ("ihmalle", "ihmalse"),
    "ihtilal": ("ihtilalle", "ihtilalse"),
    "ihtimal": ("ihtimalle", "ihtimalse"),
    "ikbal": ("ikballe", "ikbalse"),
    "ikmal": ("ikmalle", "ikmalse"),
    "illegal": ("illegalle", "illegalse"),
    "imal": ("imalle", "imalse"),
    "immoral": ("immoralle", "immoralse"),
    "imtisal": ("imtisalle", "imtisalse"),
    "infial": ("infialle", "infialse"),
    "inhilal": ("inhilalle", "inhilalse"),
    "integral": ("integralle", "integralse"),
    "intihal": ("intihalle", "intihalse"),
    "intikal": ("intikalle", "intikalse"),
    "iptal": ("iptalle", "iptalse"),
    "irtical": ("irticalle", "irticalse"),
    "irtihal": ("irtihalle", "irtihalse"),
    "ishal": ("ishalle", "ishalse"),
    "istihsal": ("istihsalle", "istihsalse"),
    "istikbal": ("istikballe", "istikbalse"),
    "istiklal": ("istiklalle", "istiklalse"),
    "işgal": ("işgalle", "işgalse"),
    "iştigal": ("iştigalle", "iştigalse"),
    "ithal": ("ithalle", "ithalse"),
    "itidal": ("itidalle", "itidalse"),
    "izmihlal": ("izmihlalle", "izmihlalse"),
    "jeotermal": ("jeotermalle", "jeotermalse"),
    "jurnal": ("jurnalle", "jurnalse"),
    "kabul": ("kabulle", "kabulse"),
    "kapital": ("kapitalle", "kapitalse"),
    "karambol": ("karambolle", "karambolse"),
    "kardinal": ("kardinalle", "kardinalse"),
    "katedral": ("katedralle", "katedralse"),
    "kefal": ("kefalle", "kefalse"),
    "kemal": ("kemalle", "kemalse"),
    "kolesterol": ("kolesterolle", "kolesterolse"),
    "kolonyal": ("kolonyalle", "kolonyalse"),
    "kontrol": ("kontrolle", "kontrolse"),
    "koramiral": ("koramiralle", "koramiralse"),
    "korgeneral": ("korgeneralle", "korgeneralse"),
    "krezol": ("krezolle", "krezolse"),
    "kriminal": ("kriminalle", "kriminalse"),
    "kristal": ("kristalle", "kristalse"),
    "legal": ("legalle", "legalse"),
    "liberal": ("liberalle", "liberalse"),
    "lokal": ("lokalle", "lokalse"),
    "lugol": ("lugolle", "lugolse"),
    "lügol": ("lügolle", "lügolse"),
    "mahal": ("mahalle", "mahalse"),
    "mareşal": ("mareşalle", "mareşalse"),
    "marjinal": ("marjinalle", "marjinalse"),
    "materyal": ("materyalle", "materyalse"),
    "mecal": ("mecalle", "mecalse"),
    "medikal": ("medikalle", "medikalse"),
    "medikososyal": ("medikososyalle", "medikososyalse"),
    "megapol": ("megapolle", "megapolse"),
    "melal": ("melalle", "melalse"),
    "mentol": ("mentolle", "mentolse"),
    "metal": ("metalle", "metalse"),
    "metanol": ("metanolle", "metanolse"),
    "meyal": ("meyalle", "meyalse"),
    "meyyal": ("meyyalle", "meyyalse"),
    "mezosefal": ("mezosefalle", "mezosefalse"),
    "minimal": ("minimalle", "minimalse"),
    "mineral": ("mineralle", "mineralse"),
    "minval": ("minvalle", "minvalse"),
    "misal": ("misalle", "misalse"),
    "miskal": ("miskalle", "miskalse"),
    "monopol": ("monopolle", "monopolse"),
    "moral": ("moralle", "moralse"),
    "müstahal": ("müstahalle", "müstahalse"),
    "müstehal": ("müstehalle", "müstehalse"),
    "müzikal": ("müzikalle", "müzikalse"),
    "müzikhol": ("müzikholle", "müzikholse"),
    "nekropol": ("nekropolle", "nekropolse"),
    "neoliberal": ("neoliberalle", "neoliberalse"),
    "nominal": ("nominalle", "nominalse"),
    "normal": ("normalle", "normalse"),
    "oligopol": ("oligopolle", "oligopolse"),
    "opal": ("opalle", "opalse"),
    "optimal": ("optimalle", "optimalse"),
    "oramiral": ("oramiralle", "oramiralse"),
    "orgeneral": ("orgeneralle", "orgeneralse"),
    "orijinal": ("orijinalle", "orijinalse"),
    "oryantal": ("oryantalle", "oryantalse"),
    "otokontrol": ("otokontrolle", "otokontrolse"),
    "oval": ("ovalle", "ovalse"),
    "parabol": ("parabolle", "parabolse"),
    "pastoral": ("pastoralle", "pastoralse"),
    "peştamal": ("peştamalle", "peştamalse"),
    "peştemal": ("peştemalle", "peştemalse"),
    "petrol": ("petrolle", "petrolse"),
    "profiterol": ("profiterolle", "profiterolse"),
    "protokol": ("protokolle", "protokolse"),
    "psikososyal": ("psikososyalle", "psikososyalse"),
    "radikal": ("radikalle", "radikalse"),
    "resital": ("resitalle", "resitalse"),
    "rical": ("ricalle", "ricalse"),
    "riyal": ("riyalle", "riyalse"),
    "rol": ("rolle", "rolse"),
    "saat": ("saatle", "saatse"),
    "santral": ("santralle", "santralse"),
    "sembol": ("sembolle", "sembolse"),
    "sinyal": ("sinyalle", "sinyalse"),
    "sistol": ("sistolle", "sistolse"),
    "sosyal": ("sosyalle", "sosyalse"),
    "spesiyal": ("spesiyalle", "spesiyalse"),
    "spiral": ("spiralle", "spiralse"),
    "sual": ("sualle", "sualse"),
    "suistimal": ("suistimalle", "suistimalse"),
    "sukutuhayal": ("sukutuhayalle", "sukutuhayalse"),
    "sürreal": ("sürrealle", "sürrealse"),
    "sürrenal": ("sürrenalle", "sürrenalse"),
    "şarampol": ("şarampolle", "şarampolse"),
    "şevval": ("şevvalle", "şevvalse"),
    "şimal": ("şimalle", "şimalse"),
    "telal": ("telalle", "telalse"),
    "terminal": ("terminalle", "terminalse"),
    "termal": ("termalle", "termalse"),
    "timsal": ("timsalle", "timsalse"),
    "total": ("totalle", "totalse"),
    "trol": ("trolle", "trolse"),
    "troll": ("trollle", "trollse"),
    "tropikal": ("tropikalle", "tropikalse"),
    "tuğgeneral": ("tuğgeneralle", "tuğgeneralse"),
    "tümamiral": ("tümamiralle", "tümamiralse"),
    "tümgeneral": ("tümgeneralle", "tümgeneralse"),
    "tuval": ("tuvalle", "tuvalse"),
    "vebal": ("veballe", "vebalse"),
    "viral": ("viralle", "viralse"),
    "visamiral": ("visamiralle", "visamiralse"),
    "viyol": ("viyolle", "viyolse"),
    "vokal": ("vokalle", "vokalse"),
    "zeval": ("zevalle", "zevalse"),
    "zühal": ("zühalle", "zühalse"),
    "zülal": ("zülalle", "zülalse"),
}
