# scripts/deepseek_corrector.py

"""
Corrects ASR reference transcriptions using the DeepSeek Language Model based on specific rules.

This script processes an input CSV file containing Automatic Speech Recognition (ASR)
'reference' and 'prediction' text pairs. For each pair, it invokes the
DeepSeek Chat API ('deepseek-chat' model) with a detailed system prompt (read from
'scripts/deepseek_prompt.md').

The core task assigned to the LLM via the prompt is to refine the 'reference' text by:
1.  **Fixing Alignment Errors:** Using the 'prediction' text as a guide to add, remove,
    or correct words at the beginning/end or within the 'reference' text that may be
    misaligned due to ASR segmentation or labeling issues. Essential content from the
    prediction might be integrated into the reference.
2.  **Correcting Language Issues:** Fixing Turkish spelling, grammar, and punctuation
    errors within the reference text.
3.  **Enforcing Turkish Localization:** Applying rules like using commas for decimals,
    removing thousand separators in numbers, placing '%' before numbers, placing currency
    symbols after numbers.
4.  **Preserving Specifics:** Keeping stopwords (e.g., "yani", "tabii") and Turkish
    accented characters (şapkalı harfler).
5.  **Identifying Mismatches:** Outputting the specific string "Hatalı etiketleme" if
    the reference and prediction texts appear completely unrelated, indicating a likely
    labeling error in the source data.

The script constrains the LLM to avoid over-reliance on potentially erroneous predictions
and to maintain the original meaning of the sentence during corrections.

The LLM's output (the corrected reference text or "Hatalı etiketleme") is then added
as a new 'corrected_reference' column to the original data. This output CSV can be
used for subsequent, more accurate ASR evaluation or data cleaning tasks.

Input Data Requirements:
    - Command-line argument `--input`: Path to the input CSV file.
    - Command-line argument `--limit` (optional): Maximum number of rows to process.
    - Input CSV format: Comma-separated, all fields quoted, UTF-8 encoding assumed.
    - Required Input Columns:
        - 'reference': The original ground truth/reference text (potentially flawed).
        - 'prediction': The ASR hypothesis text (used as context for correction).
        - 'hash': Unique identifier (used for logging/tracking).
        (Note: All other columns from the input file are preserved in the output).
    - File System: A prompt file must exist at 'scripts/deepseek_prompt.md' containing
      the detailed instructions for the LLM.
    - Environment: A '.env' file in the script's environment containing the
      'deepseek_api_key' variable for API authentication.

Output Data:
    - A new CSV file is created in the same directory as the input file.
    - The output filename is derived from the input filename by appending
      '_corrected' before the extension (e.g., 'input_data_corrected.csv').
    - Output Columns:
        - All columns from the original input CSV file.
        - 'corrected_reference': The corrected reference text generated by the DeepSeek
          API according to the prompt rules, or the string "Hatalı etiketleme" if
          a severe mismatch was detected.
"""


import csv
import argparse
from pathlib import Path
from openai import OpenAI

from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv()

# Get the API key
api_key = os.getenv('deepseek_api_key')
if not api_key:
    raise ValueError("deepseek_api_key not found in .env file")

# Use the API key when initializing the client
client = OpenAI(api_key=api_key, base_url="https://api.deepseek.com/v1")

def read_prompt(prompt_file):
    with open(prompt_file, 'r', encoding='utf-8') as f:
        return f.read()

def call_deepseek(client, prompt, reference, prediction):
    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": prompt},
            {"role": "user", "content": f"Referans: {reference}\nHipotez: {prediction}"}
        ],
        temperature=0.7
    )
    return response.choices[0].message.content

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=str, required=True, help="Input CSV file path")
    parser.add_argument("--limit", type=int, default=None, help="Limit number of rows to process")
    args = parser.parse_args()

    prompt = read_prompt("scripts/deepseek_prompt.md")
    
    input_file = Path(args.input)
    output_file = input_file.parent / f"{input_file.stem}_corrected.csv"

    with open(input_file, mode='r', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        rows = list(reader)[:args.limit] if args.limit else list(reader)

    corrected_rows = []
    for row in rows:
        correction = call_deepseek(client, prompt, row['reference'], row['prediction'])
        print(f"{row['hash']}: {correction}")
        corrected_row = row.copy()
        corrected_row['corrected_reference'] = correction
        corrected_rows.append(corrected_row)

    with open(output_file, mode='w', newline='', encoding='utf-8') as csvfile:
        fieldnames = reader.fieldnames + ['corrected_reference']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(corrected_rows)

if __name__ == "__main__":
    main()
